name: Static Code Analysis
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer:v2

      - name: "Install highest dependencies"
        run: "composer update --no-interaction --no-progress --no-suggest"

      - name: Run PHPStan
        uses: php-actions/phpstan@v3
        with:
          path: src/

      - name: "Install Phan"
        run: "composer require phan/phan"

      - name: Run Phan
        run: vendor/bin/phan --no-progress-bar --allow-polyfill-parser --output-mode checkstyle | vendor/bin/cs2pr --graceful-warnings --colorize | true

